### ISSUE TITLE
Carthage - Mockingjay for iOS

### ISSUE THREAD

**Issue by TomasLinhart** [kylef/Mockingjay#29]
I use Carthage and it uses shared schemes to build dependencies but there is only a target for Mac OS X, could iOS be added so it works with Carthage?

**Comment by kylef** [comment]
@TomasLinhart The target is not OS X, but a universal target supporting both iOS and OS X.

What error message are you seeing?

**Comment by TomasLinhart** [comment]
@kylef I don't see any error but Carthage produces only framework for Mac OS X and when I clone the repository and check the project there are only two targets. Mockingjay that has base SDK for OS X and MockingjayTests that doesn't produce any product, of course.

So there isn't any target that would have iOS as the base SDK.

You can check https://github.com/Quick/Nimble to see how others do it.

**Comment by kylef** [comment]
The Mockingjay target is capable of building iOS.

![screen shot 2015-10-14 at 11 01 50](https://cloud.githubusercontent.com/assets/44164/10492868/04106f88-7263-11e5-8053-1c3321ffeb4a.png)

Which version of Carthage are you running?

**Comment by TomasLinhart** [comment]
Oh right, I see. I have Carthage 0.8.0.

**Comment by kylef** [comment]
Carthage 0.8.0 is unsupported. Please upgrade to Carthage 0.9 which should solve this problem.

Please let me know if you have any other issues.

**Comment by TomasLinhart** [comment]
I have upgraded to Carhage 0.9.3 and it doesn't work. Now it fails while it is building.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_XCTest", referenced from:
      static ext.Mockingjay.ObjectiveC.XCTest.initialize (ObjectiveC.XCTest.Type)() -> () in XCTest.o
      @objc static ext.Mockingjay.ObjectiveC.XCTest.initialize (ObjectiveC.XCTest.Type)() -> () in XCTest.o
      l__CATEGORY_XCTest_$_Mockingjay in XCTest.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Does it work for you with Carthage?

**Comment by taiheng** [comment]
There are two issues preventing carthage from building that I've found:

Undefined symbols for XCTest framework as described by @TomasLinhart. Further up in the error log this is what is the root cause of this message:
```
ld: warning: Auto-Linking supplied '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_XCTest", referenced from:
      l__CATEGORY_XCTest_$_Mockingjay in XCTest.o
      static ext.Mockingjay.ObjectiveC.XCTest.initialize (ObjectiveC.XCTest.Type)() -> () in XCTest.o
      @objc static ext.Mockingjay.ObjectiveC.XCTest.initialize (ObjectiveC.XCTest.Type)() -> () in XCTest.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
    For some reason despite Xcode showing that Bitcode Enabled is set to No, after toggling this setting it will explicitly set ENABLE_BITCODE = NO; in project.pbxproj that fixes this issue.



The second issue that occurs is a code signing error for MockingjayTests target.
```
Check dependencies
CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 9.0'
```
There are two ways of fixing this:
- Remove MockingjayTests from the Run setting in Mackingjay scheme.
- Set the code signing explicitly for iOS SDK to 'iPhone Developer' mirroring the setting for Mockingjay framework target.

I've created a pull request that fixes these issues and will build on carthage 0.9.3, tested by cloning the repository down and running `carthage build --no-skip-current` in the repository root. See pull request kylef/mockingjay#30
